
phpVersion: '7.2'
mysqlService: 'mysqld'

#- access_compat
apacheModules:
  - expires
  - headers
  - rewrite
  - vhost_alias
  - version
  - env

phpModules:
  - xdebug
  - intl
  - opcache
  - sqlite
  - soap
  