phpVersion: '7.2'
phpbrewInstall: []   #['7.4.1', '5.6']
mysqlService: 'mysqld'

packages:
   - mc
   - git
   - curl
   - vim
   - htop
   - dos2unix
   - unzip
   - gitflow
   - phpbrew

apacheModules:
  - expires
  - headers
  - rewrite
  - vhost_alias
  - version
  - env

phpModules:
#  - apc
#  - xdebug
  - intl
  - opcache
  - sqlite
  - soap
  