# All 'vagrant up' finished for less than 10 minutes on centos7 box
#####################################################################
phpVersion: '7.2'
phpunit: false

mysqlService: 'mysqld'
vhostsJson: '/vagrant/installed_hosts.json'

vstools:
    mkvhost: 'v0.3.0'
    mkphar: 'v0.2.0'
    bumpversion: 'v0.1.0'
    ftpdeploy: 'v3.0.1'

###############################################################
# Subsystems refactored from Array to Hashes 
# but this format is used properly only for 'dotnet' for now 
subsystems:
    #docker
    phpbrew:
        version: 'latest'
    angular-cli:
        version: 'latest'
    dotnet:
        # In the begining this was the version by: 2.1.4
        # But the package MySql.Data require version: 2.2
        dotnet_core: '3.1'
        sdks: ['2.2']
        sdkUser: 'vagrant'  # Cannot be root
        #mono: 'latest'

packages:
    - mc
    - git
    - gitflow
    - gitftp
    - curl
    - vim
    - nano
    - htop
    - dos2unix
    - unzip
    - lynx

database:
    name: 'VsMyProjects'
    dump: '/vagrant/doc/sql/VsMyProjects-20201001.sql'
    
phpbrew:
    system_wide: true
    additional_dependencies: [
        'httpd-devel', 
        'libcurl-devel',
        'oniguruma-devel',
        'libsodium-devel',
        
        'libjpeg-turbo-devel',
        'libpng-devel'
    ]
    install: []   #['7.4.1', '5.6']

xdebug:
    profiler_enable: '1'
    profiler_output_name: 'cachegrind.out'
    profiler_output_dir: '/vagrant/gui_symfony/var/Xdebug'
    trace_output_name: 'trace.out'
    trace_output_dir: '/vagrant/gui_symfony/var/Xdebug'
    
apacheModules:
    - expires
    - headers
    - rewrite
    - vhost_alias
    - version
    - env
    - proxy
    - proxy_fcgi
    - proxy_http
    - proxy_html

phpModules:
#  - apc
    - xdebug
    - intl
    - opcache
    - sqlite
    - soap
    - zip
    - mongodb

git:
    userName: 'Ivan I. Atanasov'
    userEmail: 'i.atanasov77@gmail.com'

dependencies:
    CentOS:
      mysql57-community:
         type: 'yumrepo'
         url: 'https://repo.mysql.com/mysql80-community-release-el7-3.noarch.rpm'
      remi-php72:
         type: 'yumrepo'
         url: 'http://rpms.remirepo.net/enterprise/remi-release-7.rpm'
      remove-old-libzip:
         type: 'command'
         command: 'yum remove -y libzip'
      libzip-0.11:
         type: 'rpm'
         source: 'http://packages.psychotic.ninja/7/plus/x86_64/RPMS//libzip-0.11.2-6.el7.psychotic.x86_64.rpm'
         require: Exec['remove-old-libzip']
      libzip-devel-0.11:
         type: 'rpm'
         source: 'http://packages.psychotic.ninja/7/plus/x86_64/RPMS//libzip-devel-0.11.2-6.el7.psychotic.x86_64.rpm'
         require: Exec['remove-old-libzip']
      install-packages:
         type: 'command'
         command: 'yum install -y mysql-community-server php mod_php php-common php-opcache php-mcrypt php-cli php-gd php-curl php-mysql'
      php72-symlink:
         type: 'command'
         command: 'ln -s /usr/lib64/httpd/modules/libphp7.so /usr/lib64/httpd/modules/libphp7.2.so'
