# All 'vagrant up' finished for less than 10 minutes on centos7 box
#####################################################################
phpVersion: '7.2'
phpunit: false
forcePhp7Repo: true
forceMySqlComunityRepo: false
mysqlPackageName: 'mysql-server'  # Avaiable options: false, 'mysql-community-server', 'mysql-server', 'mariadb-server'

git:
    userName: 'Ivan I. Atanasov'
    userEmail: 'i.atanasov77@gmail.com'
    
vstools:
    mkvhost: 'v0.3.0'
    mkphar: 'v0.2.0'
    bumpversion: 'v0.2.0'
    ftpdeploy: 'v3.0.1'

###############################################################
# Subsystems refactored from Array to Hashes 
# but this format is used properly only for 'dotnet' for now 
subsystems:
    docker:
      enabled: false

    dotnet:
        enabled: false
        # In the begining this was the version by: 2.1.4
        # But the package MySql.Data require version: 2.2
        dotnet_core: '3.1'
        sdks: ['2.2']
        sdkUser: 'vagrant'  # Cannot be root
        #mono: 'latest'
        
    tomcat:
        enabled: false
        catalinaHome: '/opt/tomcat_7'
        sourceUrl: 'https://www-us.apache.org/dist/tomcat/tomcat-7/v7.0.106/bin/apache-tomcat-7.0.106.tar.gz'
        jdkPackage: 'java-1.8.0-openjdk-devel'
        instances:
            tomcat_9:
                catalinaHome: '/opt/tomcat_9'
                sourceUrl: 'https://downloads.apache.org/tomcat/tomcat-9/v9.0.39/bin/apache-tomcat-9.0.39.tar.gz'
        
    phpbrew:
        enabled: true
        version: 'latest'
        
        system_wide: true
        additional_dependencies:
           - httpd-devel
           - libcurl-devel
           - oniguruma-devel
           - libsodium-devel
           - libjpeg-turbo-devel
           - libpng-devel
           - libzip-devel
        install: []   #['7.4.1', '5.6'

frontendtools:
    #nodejs: latest
    nodejs: 13.12.0
    tools:
       gulp:
           version: 'latest'
       angular-cli:
           version: 'latest'
        
packages:
    - mc
    - git
    - gitflow
    - gitftp
    - curl
    - vim
    - nano
    - htop
    - dos2unix
    - unzip
    - lynx
    
apacheModules:
    - expires
    - headers
    - rewrite
    - vhost_alias
    - version
    - env
    - proxy
    - proxy_fcgi
    - proxy_http
    - proxy_html
    
    # For JSP Pages
    - proxy_ajp
    
phpModules:
    apcu:
        ini_prefix: '20-'
        provider: 'pecl'
    # ERROR: pecl/zendopcache requires PHP (version >= 5.2.0, version <= 5.5.0), installed version is 7.2.24
    #zendopcache:
    #    ini_prefix: '20-'
    #    provider: 'pecl'
    intl:
        ini_prefix: '20-'
    mbstring:
        ini_prefix: '20-'
    mongodb:
        ini_prefix: '20-'
        provider: 'pecl'
    xdebug:
        ini_prefix: '20-'
        provider: 'pecl'
        zend: true
        # see http://xdebug.org/docs/all_settings
        settings:
            'xdebug.default_enable': '1'
            'xdebug.remote_enable': '1'
            'xdebug.remote_handler': 'dbgp'
            'xdebug.remote_host': 'localhost'
            'xdebug.remote_port': '9000'
            'xdebug.remote_autostart': '0'
            'xdebug.remote_connect_back': '1'
            'xdebug.idekey': ''
            #remote_log: ''
         
            # Tracer settings
            'xdebug.trace_format': '1'
            'xdebug.trace_enable_trigger': '1'
            'xdebug.trace_output_name': 'trace.out'
            'xdebug.trace_output_dir': '/vagrant/gui_symfony/var/Xdebug'
         
            # Profiler settings
            'xdebug.profiler_enable': '1'
            'xdebug.profiler_enable_trigger': '1'
            'xdebug.profiler_output_name': 'cachegrind.out'
            'xdebug.profiler_output_dir': '/vagrant/gui_symfony/var/Xdebug'
    zip:
        ini_prefix: '20-'
    json:
        ini_prefix: '20-'
    mysqlnd:
        ini_prefix: '20-'
        multifile_settings: true
        settings:
            mysqlnd: {}
            mysql: {}
            mysqli: {}
            pdo_mysql: {}
            sysvshm: {}
    xml:
        ini_prefix: '20-'
        multifile_settings: true
        settings:
            dom: {}
            simplexml: {}
            xmlwriter: {}
            xsl: {}
            wddx: {}
            xmlreader: {}

phpMyAdmin:
    source: 'https://files.phpmyadmin.net/phpMyAdmin/5.0.4/phpMyAdmin-5.0.4-all-languages.zip'
    targetDirName: 'phpMyAdmin-5.0.4-all-languages'

databases:
    default:
        name: 'VsMyProjects'
        dump: '/vagrant/doc/sql/VsMyProjects-20201001.sql'
        
ansible:
    pathRoles: '/vagrant/ansible.d/playbook/roles/'
    logPath: '/vagrant/ansible.d/log'
    galaxyRoles: []
    # Example
    ##################################
    #galaxyRoles:
    #    - geerlingguy.java
    #    - geerlingguy.jenkins
