
phpVersion: '7.2'
mysqlService: 'mysqld'

apacheModules:
  - expires
  - headers
  - rewrite
  - vhost_alias
  - version
  - env
  - access_compat

phpModules:
  - xdebug
  - intl
  - opcache
  - sqlite
  - soap
  