
phpVersion: '7.2'
phpbrewPhpVersion: '7.4.1'
mysqlService: 'mysqld'

#- access_compat

packages:
  - mc
  - git
  - gitflow
  - curl
  - vim
  - htop
  - dos2unix
  - unzip
  - phpbrew

apacheModules:
  - expires
  - headers
  - rewrite
  - vhost_alias
  - version
  - env

phpModules:
#  - apc
#  - xdebug
  - intl
  - opcache
  - sqlite
  - soap
  